---
title: "20191121 class"
author: "jacky wang"
date: "2020/9/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)

# 設定要使用的python（可能因要使用不同版本的python而路徑有所改變）
use_python("C:\\Users\\User\\anaconda3\\envs\\pyClassEnv_ntpu\\python.exe", required = T)
# 在名為classEnvironment的沙盒下寫python
use_condaenv("pyClassEnv_ntpu", required = T)
```
若無法執行set up chunk，按Session－＞按Restart R

**技巧**

按小齒輪－＞按chunk output in console：讓console可編譯Python（>>> Python code）。
  在console打exit，就會回復原狀（> R code）。

在console裡打“repl_python()”，讓console可編譯Python（>>> Python code）。

shift + Tab：回彈兩格。

**連結**

https://opendata.culture.tw/ --> 文化資料開放服務網





# CH8 Numpy



# dim, size & shape

```{python}
import numpy as np
```

```{python}

x_23 = np.array(
  [
    [-1, 1, 5], 
    [0, 7, 4]
  ]
)

```

```{python}

x_23.shape    # ? by ? matrix
x_23.ndim    # How many axis? 

```

## vectors to matrix

```{python}

x0 = np.array([[2,3,5,7,9,11]])
x0
x0.shape

x0.shape = (2, 3)
x0

```

另存為新的matrix：

傳統法
```{python}

x1 = x0.copy()
x1.shape = (3, 2)
x0; x1

```

reshape method（不會改變原始值）
```{python}

del x1

x1 = x0.reshape(3, 2)
x0; x1

```



# array & flat array

array
```{python}

x1 = np.array([[ 1., 2., 3.]])    # row vector
x2 = np.array([[1.],[2.],[3.]])    # column vector
x1; x2

```

flat array（少了外層的[]）
```{python}

x0 = np.array([ 1., 0., 0.])
print(x0)
x0.shape    # (3,) means (1, 3)
x0.ndim    # only one axis

```

flat array與真array運算時會被當成一列
```{python}

x0 = np.array([ 1., 0., 0.])
x1 = np.array([[0., 1., 1.]])
x2 = np.array([[0.], [1.], [1.]])
x0; x1; x2

x0.shape
x1.shape
x2.shape

```

```{python}

x0 + x1
x0 + x2    # broadcasting

```

上述之 x0 + x2 等於
```{python}

a0 = np.array(
  [
    [1., 0., 0.], 
    [1., 0., 0.], 
    [1., 0., 0.]
  ]
)

a2 = np.array(
  [
    [0., 0., 0.], 
    [1., 1., 1.], 
    [1., 1., 1.]
  ]
)

a0 + a2

```



# elementwise operations

照位置一一做運算

```{python}

a = np.array(
  [
    [-1., 4., -6.],
    [1., 4., 6.]
  ]
) 

b = np.array(
  [
    [1., 2., 3.],
    [1., 2., 3.]
  ]
)  

```

```{python}

a*b
a/b

```



# broadcasting

當矩陣運算所需的conformability條件不滿足時，
Python自動更動矩陣的dimension（前提是矩陣須滿足Python的compatibility條件），
進而滿足conformability的條件。
  dimension：指列、行數。(d0, d1)
  conformability：指兩矩陣列、行數都相等。

```{python}



```



# vectorized function

```{python}

def addsub(a,b):
    if a > b:
      return a - b
    else:
      return a + b

```

```{python}

addsub(2, 3)
addsub([2, 4], [3, -1])    # wrong! 
# addsub(
#   np.array([2, 4]), 
#   np.array([3, -1])
# )    # wrong! 

```
此函數input只能是scalar

使函數可以input array
```{python}

vec_addsub = np.vectorize(addsub)

vec_addsub(
  np.array([2, 4]), 
  np.array([3, -1])
)

vec_addsub(
  [2, 4], 
  [3, -1]
)

```

已內建的函數（可input array）：
  https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs



# 矩陣運算

## 矩陣相乘

```{python}

A = np.array(
  [
    [2, 4],
    [1, 3]
  ]
)

B = np.array(
  [
    [-1, 2],
    [-3, 4]
  ]
)

A*B    # wrong! 
A@B

```

## 矩陣轉置

```{python}

matrix1 = np.array(
  [
    [2, 3, -1], 
    [8, 11, 5]
  ]
)

matrix1
matrix1.T

```

## 反矩陣 & 行列式

```{python}
from numpy.linalg import inv, det
```

計算
$$\hat{\beta} = (X^TX)^{-1} X^TY $$
```{python}

y = np.array([[2,3,4,6]]).T
x = np.array(
  [
    [1,1,1,1],
    [0,-2,4,7]
  ]
).T

```

```{python}

def betaFun(x, y): 
    x1 = x.T @ x
    x2 = x.T @ y
    return inv(x1) @ x2

betaFun(x, y)

```

### practice1

```{python}

y = np.array([[2, -1, 3]]).T
x1 = np.array([[1, -1, 1]]).T
x2 = np.array([[4, 7, 3]]).T

```

找出y在x1、x2平面上的正交投射
```{python}

X = np.column_stack([x1, x2])

Px = X @ inv(X.T@X) @ X.T

y_hat = Px @ y

```

```{python}

e = y - y_hat
y_hat.T @ e    # inner product = 0

```

flat array不用轉置就可以矩陣相乘，但array不行。
```{python}

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a@b

c = np.array([[1.0, 2.0, 3.0]]).T
d = np.array([[2.0, 2.0, 2.0]]).T
# c@d    # error
c.T@d

```

計算y到x1、x2平面最短的距離
```{python}

(e.T@e)**(1/2)

```

### practice2

1. 定義常態分配之PDF
```{python}

def normalPDF(x, mean=0, sigma=1): 
    a = (2 * np.pi * sigma**2)**(-0.5)
    b = np.exp(
      -((x - mean)**2 / 2*sigma**2)
    )
    return a*b

```

```{python}

normalPDF(0)
normalPDF(1)
# normalPDF([0, 1])    # not a vectorized function

```

```{python}

vec_normalPDF = np.vectorize(normalPDF)
vec_normalPDF([0, 1, -1])

```

2. 
$$\epsilon_i=y_i-\hat{y}_i$$
假設
$$\epsilon_i \stackrel{iid}{\sim} N(0,1)$$
```{python}

y = np.array([[2,3,4,6]]).T
x = np.array(
  [
    [1,1,1,1],
    [0,-2,4,7]
  ]
).T

x; y

```

計算每個$\epsilon_i$的pdf
```{python}

y_hat = x@inv(x.T@x)@x.T @ y
y_hat

e = y - y_hat
e

vec_normalPDF(e)

```

3. 取其 ln 再相加
```{python}

np.log(vec_normalPDF(e)).sum()

```






